CREATE TABLE AppUser (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL
);

CREATE TABLE Quiz (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userId INT UNSIGNED NOT NULL,
    name VARCHAR(512) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT 0,
    private BOOLEAN NOT NULL DEFAULT 0,
    multipleTries BOOLEAN NOT NULL DEFAULT 1,
    FOREIGN KEY (userId) REFERENCES AppUser(id) ON DELETE CASCADE
);

CREATE TABLE QuizQuestion (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    quizId INT UNSIGNED NOT NULL,
    label VARCHAR(512) NOT NULL,
    FOREIGN KEY (quizId) REFERENCES Quiz(id) ON DELETE CASCADE
);

CREATE TABLE QuizOption (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    questionId INT UNSIGNED NOT NULL,
    label VARCHAR(512) NOT NULL,
    correct BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (questionId) REFERENCES QuizQuestion(id) ON DELETE CASCADE
);

CREATE TABLE Invitation (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    quizId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    FOREIGN KEY (quizId) REFERENCES Quiz(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES AppUser(id) ON DELETE CASCADE
);

CREATE TABLE QuizAnswer (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    questionId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    FOREIGN KEY (questionId) REFERENCES QuizOption(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES AppUser(id) ON DELETE CASCADE
);